apiVersion: v1
kind: ServiceAccount
metadata:
  name: analyzer
  namespace: stube
  labels:
    app: analyzer
    value-stream: stube
# The CI's deploy job links the gitlab-registry pull secret to this SA
# via `oc secrets link analyzer gitlab-registry --for=pull`.
